# Generated by Django 3.1.6 on 2021-02-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Data',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
