# Generated by Django 3.1.6 on 2021-02-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'DEPARTMENTS',
            },
        ),
    ]
