# Generated by Django 3.1.6 on 2021-02-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0002_departments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_data',
            table='EMPLOYEE_DATA',
        ),
    ]
