# Generated by Django 3.1.6 on 2021-02-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0003_auto_20210207_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findemo.departments')),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findemo.employee_data')),
            ],
            options={
                'unique_together': {('emp_no', 'dept_no')},
            },
        ),
    ]
