# Generated by Django 3.1.6 on 2021-02-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0004_dept_manager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dept_manager',
            table='DEPT_MANAGER',
        ),
    ]
