# Generated by Django 3.1.6 on 2021-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0006_dept_emp_salaries_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=5),
        ),
        migrations.AlterModelTable(
            name='employee_data',
            table='EMPLOYEES',
        ),
    ]
