# Generated by Django 3.1.6 on 2021-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0007_auto_20210207_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='first_name',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='last_name',
            field=models.CharField(max_length=16),
        ),
    ]
