# Generated by Django 3.1.6 on 2021-02-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findemo', '0008_auto_20210207_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='emp_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
